include:
  - ldviewer.yml

networks:
  traefik-net:
    driver: bridge

services:
  traefik:
    image: traefik:v3.5
    command:
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:8080"
      - "--providers.file.filename=/etc/traefik/traefik_dynamic.yml"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
    networks:
      - traefik-net
    restart: unless-stopped
